### ISSUE TITLE
Import core formulae

### ISSUE THREAD

**Issue by dpo** [dpo/homebrew-openblas#2]
- [x] arpack: #4 (6baf4d8fb203e3325298cb86178ad429c17427e7)
- [x] ceres-solver: #15 (27d02250b7306f54f371708da850eb91a5a298a0)
- [ ] cminpack
- [ ] dlib
- [ ] eigen
- [ ] eigen@3.2
- [x] numpy: #10 (c5e4b2d6c2866f1be50ed823aa38620e84729d28)
- [x] octave: #41 
- [x] qrupdate: #6 (1dbf9fae1567bc8f2bfff5bdc58f37357730edd4)
- [x] r: #9 (0e68e22c1c8f8c240e966edf568025c8730478e2)
- [ ] rubberband
- [x] scalapack: #7 (ba26d3ee3bc82a68ea1963887ec20de4539bd93e)
- [x] scipy: #13 (07df3cae3c14c54b169f94dbecf3cec199af9276)
- [x] suite-sparse: #8 (9f948267a5e0b4c615213cf73188fe102da55e79)
- [x] superlu: #16 (8ffbaad872f9835c5d24e77d751453b54e284a38)
- [ ] viennacl
